// Jester Treasure — offline mint tool.
//
// Regenerates the byte payloads embedded in:
//   • lib/env/routing_endpoint.dart
//   • lib/env/attribution_seed.dart
//   • lib/core/net_channel.dart   (Chromium/WebKit UA fragments)
//
// Run with:
//   dart run tool/mint_secrets.dart
//
// NEVER pipe the plaintext through shell one-liners — some hosts (PowerShell
// on Windows in particular) will silently truncate the integer values above
// 0x7FFFFFFF and produce garbage payloads. The Dart VM handles the math
// correctly on every platform.

import '../lib/env/cipher.dart';

void main() {
  final entries = <String, String>{
    'ROUTING_HOST      ': 'https://jestertreasure.com',
    'ROUTING_PATH      ': '/config.php',
    'ATTRIBUTION_KEY   ': 'AF_DEV_KEY_PLACEHOLDER',
    'MESSAGING_PROJECT ': '000000000000',
    'GCD_HOST          ': 'https://gcdsdk.appsflyer.com',
    'GCD_PATH          ': '/install_data/v4.0/',
    'UA_CHROME_FRAGMENT': '149.0.7827.163',
    'UA_WEBKIT_FRAGMENT': '537.36',
  };

  final buf = StringBuffer();
  buf.writeln('// Auto-generated by tool/mint_secrets.dart — do not edit');
  buf.writeln('// (paste the arrays back into their respective .dart files)');
  buf.writeln('');

  entries.forEach((label, plain) {
    final sealed = seal(plain);
    buf.writeln('// $label  (${plain.length} bytes)');
    buf.writeln('// plaintext: "$plain"');
    buf.writeln('const _bytes_${label.trim()} = <int>[');
    final chunks = <String>[];
    for (int i = 0; i < sealed.length; i += 12) {
      final end = (i + 12).clamp(0, sealed.length);
      chunks.add('  ${sealed.sublist(i, end).map((b) => "0x${b.toRadixString(16).padLeft(2, '0')}").join(", ")},');
    }
    buf.writeln(chunks.join('\n'));
    buf.writeln('];');
    buf.writeln('');
  });

  print(buf.toString());
}
